### PR TITLE
Luma ac

### PR DESCRIPTION
**Pull request by tglik**
This saves about 10% of luma total on relevant videos.
Now the 8meg video total is 96% instead of 101%

### CODE REVIEW

**Comment by danielrh** [comment]
Thanks for the diff...it works well on your branch but when rebased against master due to leaving uninitailized memory in the AC components that are masked out, so it doesn't roundtrip
Patrick knows how to fix the bug: I think he will land a fix soon

**Comment by danielrh** [comment]
won't merge until the fix is in

**Comment by pathorn** [comment]
My version of the fix is in h264priors branch.

**Comment by danielrh** [comment]
Rebased and merged

**Comment by alanshieh** [comment]
Just realized that i didnt do any direct testing of my function to compute
the pixel level average (i did test a related function). Someone should use
that function to dump a bitmap, & do some visual debugging

**Pull request closed without merging**
